laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('produtos/{categoria}', 'ProdutosController@index')->name('produtos.categorias');
    Route::get('produtos/{categoria}/{produto}', 'ProdutosController@show')->name('produtos.detalhes');
    Route::post('mais-informacoes/{produto}', 'ContatoController@postMaisInformacoes')->name('mais-informacoes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en', 'es'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('contatos/recebidos/{recebidos}/toggle', ['as' => 'painel.contatos.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::get('contatos/mais-informacoes/{informacoes}/toggle', ['as' => 'painel.contatos.mais-informacoes.toggle', 'uses' => 'ContatosInformacoesController@toggle']);

        Route::resource('usuarios', 'UsuariosController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('contatos/recebidos', 'ContatosRecebidosController');
        Route::resource('contatos/mais-informacoes', 'ContatosInformacoesController');
        Route::resource('contatos', 'ContatosController');
        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('categorias', 'CategoriasController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produto}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'produtos_imagens']]);
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BannersRequest;
use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannersRequest $request, Banner $banner)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $banner->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Banner $banner)
    {
        try {
            $banner->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriasRequest;
use App\Models\Categoria;

class CategoriasController extends Controller
{
    public function index()
    {
        $categorias = Categoria::ordenados()->get();

        return view('painel.categorias.index', compact('categorias'));
    }

    public function edit(Categoria $categoria)
    {
        return view('painel.categorias.edit', compact('categoria'));
    }

    public function update(CategoriasRequest $request, Categoria $categoria)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo_pt, '-');

            if (isset($input['capa'])) $input['capa'] = Categoria::upload_capa();

            $categoria->update($input);

            return redirect()->route('painel.categorias.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConfiguracoesRequest;
use App\Models\Configuracao;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracao::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracao $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracao::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContatosRequest;
use App\Models\Contato;

class ContatosController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contatos.edit', compact('contato'));
    }

    public function update(ContatosRequest $request, Contato $contato)
    {
        try {
            $input = $request->all();

            $contato->update($input);

            return redirect()->route('painel.contatos.index')->with('success', 'Informações alteradas com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosInformacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\ContatoInformacao;
use App\Models\Produto;

class ContatosInformacoesController extends Controller
{
    public function index()
    {
        $contatosinfos = ContatoInformacao::orderBy('created_at', 'DESC')->get();
        $produtos = Produto::all();

        return view('painel.contatos.informacoes.index', compact('contatosinfos', 'produtos'));
    }

    public function show($contatoInfo)
    {
        $contato = ContatoInformacao::where('id', $contatoInfo)->first();
        $contato->update(['lido' => 1]);

        $produto = Produto::where('id', $contato->produto_id)->first();

        return view('painel.contatos.informacoes.show', compact('contato', 'produto'));
    }

    public function destroy($contatoInfo)
    {
        try {
            $contato = ContatoInformacao::where('id', $contatoInfo)->first();
            $contato->delete();

            return redirect()->route('painel.contatos.mais-informacoes.index')->with('success', 'Mensagem excluída com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: ' . $e->getMessage()]);
        }
    }

    public function toggle($contatoInfo)
    {
        try {
            $contato = ContatoInformacao::where('id', $contatoInfo)->first();
            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contatos.mais-informacoes.index')->with('success', 'Mensagem alterada com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contatos.recebidos.index', compact('contatosrecebidos'));
    }

    public function show($contatoRecebido)
    {
        $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
        $contato->update(['lido' => 1]);

        return view('painel.contatos.recebidos.show', compact('contato'));
    }

    public function destroy($contatoRecebido)
    {
        try {
            $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
            $contato->delete();

            return redirect()->route('painel.contatos.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: ' . $e->getMessage()]);
        }
    }

    public function toggle($contatoRecebido)
    {
        try {
            $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contatos.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\HomeRequest;
use App\Models\Home;

class HomeController extends Controller
{
    public function index()
    {
        $registro = Home::first();

        return view('painel.home.edit', compact('registro'));
    }

    public function update(HomeRequest $request, Home $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_artista'])) $input['imagem_artista'] = Home::upload_imagem_artista();
            if (isset($input['imagem_design'])) $input['imagem_design'] = Home::upload_imagem_design();

            $registro->update($input);

            return redirect()->route('painel.home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Helpers\CropImage;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class PainelController extends Controller
{
    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

    private $image_config = [
        'width'  => 980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/editor/'
    ];

    public function imageUpload(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return response()->json($response);
    }
}

laravel/app/Http/Controllers/Painel/PoliticaDePrivacidadeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\PoliticaDePrivacidadeRequest;
use App\Models\PoliticaDePrivacidade;

class PoliticaDePrivacidadeController extends Controller
{
    public function index()
    {
        $registro = PoliticaDePrivacidade::first();

        return view('painel.politica-de-privacidade.edit', compact('registro'));
    }

    public function update(PoliticaDePrivacidadeRequest $request, PoliticaDePrivacidade $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.politica-de-privacidade.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/ProdutosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categoria;
use App\Models\Produto;
use App\Models\ProdutoImagem;

class ProdutosController extends Controller
{
    public function index($categoria_slug)
    {
        $categoria = Categoria::where('slug', $categoria_slug)->first();

        $categorias = Categoria::ordenados()->get();

        $produtos = Produto::categoria($categoria->id)->ordenados()->get();
        $imagens = ProdutoImagem::ordenados()->get();

        return view('frontend.produtos-categorias', compact('categoria', 'categorias', 'produtos', 'imagens'));
    }

    public function show($categoria_slug, $produto_slug)
    {
        $categoria = Categoria::where('slug', $categoria_slug)->first();
        $categorias = Categoria::ordenados()->get();

        $produto = Produto::where('slug', $produto_slug)->where('categoria_id', $categoria->id)->first();
        $imagens = ProdutoImagem::produto($produto->id)->ordenados()->get();
        $capa = $imagens->first();

        $proximo = Produto::where('categoria_id', $categoria->id)->ordenados()->where('ordem', '>', $produto->ordem)->first();
        $anterior = Produto::where('categoria_id', $categoria->id)->where('ordem', '<', $produto->ordem)->orderBy('ordem', 'desc')->first();

        return view('frontend.produtos-detalhes', compact('produto', 'imagens', 'categoria', 'categorias', 'capa', 'proximo', 'anterior'));
    }
}

laravel/resources/views/painel/produtos/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Produtos |</small> Adicionar Produto</h2>
</legend>

{!! Form::open(['route' => 'painel.produtos.store', 'files' => true]) !!}

@include('painel.produtos.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Produtos |</small> Editar Produto</h2>
</legend>

{!! Form::model($produto, [
'route' => ['painel.produtos.update', $produto->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.produtos.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/produtos/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('categoria_id', 'Categoria') !!}
    {!! Form::select('categoria_id', $categorias , old('categoria_id'), ['class' => 'form-control']) !!}
</div>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('titulo_pt', 'Título [PT]') !!}
            {!! Form::text('titulo_pt', null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('titulo_en', 'Título [EN]') !!}
            {!! Form::text('titulo_en', null, ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('titulo_es', 'Título [ES]') !!}
            {!! Form::text('titulo_es', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('descricao_pt', 'Descrição [PT]') !!}
            {!! Form::textarea('descricao_pt', null, ['class' => 'form-control ckeditor', 'data-editor' => 'padrao']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('descricao_en', 'Descrição [EN]') !!}
            {!! Form::textarea('descricao_en', null, ['class' => 'form-control ckeditor', 'data-editor' => 'padrao']) !!}
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            {!! Form::label('descricao_es', 'Descrição [ES]') !!}
            {!! Form::textarea('descricao_es', null, ['class' => 'form-control ckeditor', 'data-editor' => 'padrao']) !!}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 form-group">
        {!! Form::label('peso_pt', 'Peso [PT]') !!}
        {!! Form::text('peso_pt', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('peso_en', 'Peso [EN]') !!}
        {!! Form::text('peso_en', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('peso_es', 'Peso [ES]') !!}
        {!! Form::text('peso_es', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="row">
    <div class="col-md-4 form-group">
        {!! Form::label('diametro_pt', 'Diâmetro [PT]') !!}
        {!! Form::text('diametro_pt', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('diametro_en', 'Diâmetro [EN]') !!}
        {!! Form::text('diametro_en', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('diametro_es', 'Diâmetro [ES]') !!}
        {!! Form::text('diametro_es', null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="row">
    <div class="col-md-4 form-group">
        {!! Form::label('altura_pt', 'Altura [PT]') !!}
        {!! Form::text('altura_pt', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('altura_en', 'Altura [EN]') !!}
        {!! Form::text('altura_en', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('altura_es', 'Altura [ES]') !!}
        {!! Form::text('altura_es', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="row">
    <div class="col-md-4 form-group">
        {!! Form::label('largura_pt', 'Largura [PT]') !!}
        {!! Form::text('largura_pt', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('largura_en', 'Largura [EN]') !!}
        {!! Form::text('largura_en', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('largura_es', 'Largura [ES]') !!}
        {!! Form::text('largura_es', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="row">
    <div class="col-md-4 form-group">
        {!! Form::label('profundidade_pt', 'Profundidade [PT]') !!}
        {!! Form::text('profundidade_pt', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('profundidade_en', 'Profundidade [EN]') !!}
        {!! Form::text('profundidade_en', null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-4 form-group">
        {!! Form::label('profundidade_es', 'Profundidade [ES]') !!}
        {!! Form::text('profundidade_es', null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="well form-group">
    {!! Form::label('desenho', 'Desenho') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/produtos/'.$produto->desenho) }}" style="display:block; margin-bottom: 10px; max-width: 100%; max-height:200px">
    @endif
    {!! Form::file('desenho', ['class' => 'form-control']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.produtos.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/produtos/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        Produtos
        <a href="{{ route('painel.produtos.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Produto</a>
    </h2>
</legend>

<h4 class="titulo-filtro">Categorias:</h4>
<div class="lista-filtro">
    <a href="{{ route('painel.produtos.index') }}" class="item {{ (!isset($_GET['categoria'])) ? 'active' : '' }}">Todos</a>
    @foreach($categorias as $categoria)
    <a href="{{ route('painel.produtos.index', ['categoria' => $categoria->id]) }}" class="item {{ (isset($_GET['categoria']) && $_GET['categoria'] == $categoria->id) ? 'active' : '' }}">{{ $categoria->titulo_pt }}</a>
    @endforeach
</div>

@if(!count($produtos))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="produtos">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Categoria</th>
            <th>Título</th>
            <th>Gerenciar</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($produtos as $produto)
        <tr class="tr-row" id="{{ $produto->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            @php
            $categoria = $categorias->find($produto->categoria_id)->titulo_pt;
            @endphp
            <td>{{ $categoria }}</td>
            <td>{{ $produto->titulo_pt }}</td>
            <td>
                <a href="{{ route('painel.produtos.imagens.index', $produto->id) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Imagens
                </a>
            </td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.produtos.destroy', $produto->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.produtos.edit', $produto->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection