laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('produtos/{categoria}', 'ProdutosController@index')->name('produtos.categorias');
    Route::get('produtos/{categoria}/{produto}', 'ProdutosController@show')->name('produtos.detalhes');
    Route::post('mais-informacoes/{produto}', 'ContatoController@postMaisInformacoes')->name('mais-informacoes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en', 'es'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('contatos/recebidos/{recebidos}/toggle', ['as' => 'painel.contatos.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::get('contatos/mais-informacoes/{informacoes}/toggle', ['as' => 'painel.contatos.mais-informacoes.toggle', 'uses' => 'ContatosInformacoesController@toggle']);

        Route::resource('usuarios', 'UsuariosController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('contatos/recebidos', 'ContatosRecebidosController');
        Route::resource('contatos/mais-informacoes', 'ContatosInformacoesController');
        Route::resource('contatos', 'ContatosController');
        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('categorias', 'CategoriasController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produto}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'produtos_imagens']]);
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BannersRequest;
use App\Models\Banner;

class BannersController extends Controller
{
    public function index()
    {
        $banners = Banner::ordenados()->get();

        return view('painel.banners.index', compact('banners'));
    }

    public function create()
    {
        return view('painel.banners.create');
    }

    public function store(BannersRequest $request)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            Banner::create($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Banner $banner)
    {
        return view('painel.banners.edit', compact('banner'));
    }

    public function update(BannersRequest $request, Banner $banner)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Banner::upload_imagem();

            $banner->update($input);

            return redirect()->route('painel.banners.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Banner $banner)
    {
        try {
            $banner->delete();

            return redirect()->route('painel.banners.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/CategoriasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoriasRequest;
use App\Models\Categoria;

class CategoriasController extends Controller
{
    public function index()
    {
        $categorias = Categoria::ordenados()->get();

        return view('painel.categorias.index', compact('categorias'));
    }

    public function edit(Categoria $categoria)
    {
        return view('painel.categorias.edit', compact('categoria'));
    }

    public function update(CategoriasRequest $request, Categoria $categoria)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo_pt, '-');

            if (isset($input['capa'])) $input['capa'] = Categoria::upload_capa();

            $categoria->update($input);

            return redirect()->route('painel.categorias.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ConfiguracoesRequest;
use App\Models\Configuracao;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracao::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracao $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracao::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContatosRequest;
use App\Models\Contato;

class ContatosController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contatos.edit', compact('contato'));
    }

    public function update(ContatosRequest $request, Contato $contato)
    {
        try {
            $input = $request->all();

            $contato->update($input);

            return redirect()->route('painel.contatos.index')->with('success', 'Informações alteradas com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosInformacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\ContatoInformacao;
use App\Models\Produto;

class ContatosInformacoesController extends Controller
{
    public function index()
    {
        $contatosinfos = ContatoInformacao::orderBy('created_at', 'DESC')->get();
        $produtos = Produto::all();

        return view('painel.contatos.informacoes.index', compact('contatosinfos', 'produtos'));
    }

    public function show($contatoInfo)
    {
        $contato = ContatoInformacao::where('id', $contatoInfo)->first();
        $contato->update(['lido' => 1]);

        $produto = Produto::where('id', $contato->produto_id)->first();

        return view('painel.contatos.informacoes.show', compact('contato', 'produto'));
    }

    public function destroy($contatoInfo)
    {
        try {
            $contato = ContatoInformacao::where('id', $contatoInfo)->first();
            $contato->delete();

            return redirect()->route('painel.contatos.mais-informacoes.index')->with('success', 'Mensagem excluída com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: ' . $e->getMessage()]);
        }
    }

    public function toggle($contatoInfo)
    {
        try {
            $contato = ContatoInformacao::where('id', $contatoInfo)->first();
            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contatos.mais-informacoes.index')->with('success', 'Mensagem alterada com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contatos.recebidos.index', compact('contatosrecebidos'));
    }

    public function show($contatoRecebido)
    {
        $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
        $contato->update(['lido' => 1]);

        return view('painel.contatos.recebidos.show', compact('contato'));
    }

    public function destroy($contatoRecebido)
    {
        try {
            $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
            $contato->delete();

            return redirect()->route('painel.contatos.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: ' . $e->getMessage()]);
        }
    }

    public function toggle($contatoRecebido)
    {
        try {
            $contato = ContatoRecebido::where('id', $contatoRecebido)->first();
            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contatos.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\HomeRequest;
use App\Models\Home;

class HomeController extends Controller
{
    public function index()
    {
        $registro = Home::first();

        return view('painel.home.edit', compact('registro'));
    }

    public function update(HomeRequest $request, Home $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_artista'])) $input['imagem_artista'] = Home::upload_imagem_artista();
            if (isset($input['imagem_design'])) $input['imagem_design'] = Home::upload_imagem_design();

            $registro->update($input);

            return redirect()->route('painel.home.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/PainelController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Helpers\CropImage;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class PainelController extends Controller
{
    public function index()
    {
        return view('painel.home');
    }

    public function order(Request $request)
    {
        if (!$request->ajax()) return false;

        $data  = $request->input('data');
        $table = $request->input('table');

        for ($i = 0; $i < count($data); $i++) {
            DB::table($table)->where('id', $data[$i])->update(array('ordem' => $i + 1));
        }

        return json_encode($data);
    }

    private $image_config = [
        'width'  => 980,
        'height' => null,
        'upsize' => true,
        'path'   => 'assets/img/editor/'
    ];

    public function imageUpload(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'imagem' => 'image|required'
        ]);

        if ($validator->fails()) {
            $response = [
                'error'   => true,
                'message' => 'O arquivo deve ser uma imagem.'
            ];
        } else {
            $imagem   = CropImage::make('imagem', $this->image_config);
            $response = [
                'filepath' => asset($this->image_config['path'] . $imagem)
            ];
        }

        return response()->json($response);
    }
}

laravel/app/Http/Controllers/Painel/PoliticaDePrivacidadeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\PoliticaDePrivacidadeRequest;
use App\Models\PoliticaDePrivacidade;

class PoliticaDePrivacidadeController extends Controller
{
    public function index()
    {
        $registro = PoliticaDePrivacidade::first();

        return view('painel.politica-de-privacidade.edit', compact('registro'));
    }

    public function update(PoliticaDePrivacidadeRequest $request, PoliticaDePrivacidade $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.politica-de-privacidade.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
<div class="alert alert-block alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {!! session('success') !!}
</div>
@endif

@if($errors->any())
<div class="alert alert-block alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    @foreach($errors->all() as $error)
    {!! $error !!}<br>
    @endforeach
</div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*', 'painel.politica-de-privacidade*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}" class="link-nav-painel">Política de Privacidade</a>
                        </li>
                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}">Relatório de Cookies</a>
                        </li>
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">

    <li class="dropdown @if(Tools::routeIs(['painel.banners*', 'painel.home*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.home.index')) class="active" @endif>
                <a href="{{ route('painel.home.index') }}">Dados</a>
            </li>
            <li @if(Tools::routeIs('painel.banners*')) class="active" @endif>
                <a href="{{ route('painel.banners.index') }}">Banners</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.categorias*')) class="active" @endif>
        <a href="{{ route('painel.categorias.index') }}">Categorias</a>
    </li>

    <li @if(Tools::routeIs('painel.produtos*')) class="active" @endif>
        <a href="{{ route('painel.produtos.index') }}">Produtos</a>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.contatos*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contatos
            @if($contatosNaoLidos >= 1 || $contatosInfosNaoLidos >= 1)
            @php $total = $contatosNaoLidos + $contatosInfosNaoLidos; @endphp
            <span class="label label-success" style="margin-left:3px;">{{ $total }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contatos.index')) class="active" @endif>
                <a href="{{ route('painel.contatos.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.contatos.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contatos.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
            <li @if(Tools::routeIs('painel.contatos.mais-informacoes*')) class="active" @endif>
                <a href="{{ route('painel.contatos.mais-informacoes.index') }}">
                    Mais Informações
                    @if($contatosInfosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosInfosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>

</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>

<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>

</body>

</html>