laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('produtos/{categoria}', 'ProdutosController@index')->name('produtos.categorias');
    Route::get('produtos/{categoria}/{produto}', 'ProdutosController@show')->name('produtos.detalhes');
    Route::post('mais-informacoes/{produto}', 'ContatoController@postMaisInformacoes')->name('mais-informacoes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Idiomas
    Route::get('lang/{idioma?}', function ($idioma = 'pt') {
        if (in_array($idioma, ['pt', 'en', 'es'])) {
            Session::put('locale', $idioma);
        }
        return redirect()->back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('contatos/recebidos/{recebidos}/toggle', ['as' => 'painel.contatos.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::get('contatos/mais-informacoes/{informacoes}/toggle', ['as' => 'painel.contatos.mais-informacoes.toggle', 'uses' => 'ContatosInformacoesController@toggle']);

        Route::resource('usuarios', 'UsuariosController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::resource('contatos/recebidos', 'ContatosRecebidosController');
        Route::resource('contatos/mais-informacoes', 'ContatosInformacoesController');
        Route::resource('contatos', 'ContatosController');
        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('banners', 'BannersController');
        Route::resource('categorias', 'CategoriasController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('produtos', 'ProdutosController');
        Route::get('produtos/{produto}/imagens/clear', [
            'as'   => 'painel.produtos.imagens.clear',
            'uses' => 'ProdutosImagensController@clear'
        ]);
        Route::resource('produtos.imagens', 'ProdutosImagensController', ['parameters' => ['imagens' => 'produtos_imagens']]);
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Models/Contato.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Contato extends Model
{
    protected $table = 'contatos';

    protected $guarded = ['id'];
}

laravel/app/Models/ContatoRecebido.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ContatoRecebido extends Model
{
    protected $table = 'contatos_recebidos';

    protected $guarded = ['id'];

    public function getCreatedAtAttribute($date)
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $date)->format('d/m/Y');
    }

    public function getCreatedAtOrderAttribute()
    {
        return \Carbon\Carbon::createFromFormat('d/m/Y', $this->created_at)->format('Y-m-d');
    }

    public function scopeArquitetoDesign($query)
    {
        return $query->where('arquiteto_design', '!=', 1);
    }

    public function scopeNaoLidos($query)
    {
        return $query->where('lido', '!=', 1);
    }

    public function countNaoLidos()
    {
        return $this->naoLidos()->count();
    }
}

laravel/app/Http/Controllers/ContatoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ContatosInformacoesRequest;
use App\Http\Requests\ContatosRecebidosRequest;
use App\Models\Contato;
use App\Models\ContatoInformacao;
use App\Models\ContatoRecebido;
use App\Models\Produto;
use Illuminate\Support\Facades\Mail;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('frontend.contato', compact('contato'));
    }

    public function post(ContatosRecebidosRequest $request, ContatoRecebido $contatoRecebido)
    {
        $data = $request->all();
        
        if($request->arquiteto_design) {
            $data['arquiteto_design'] = $request->arquiteto_design;
        } else {
            $data['arquiteto_design'] = 0;
        }

        $contatoRecebido->create($data);
        $this->sendMail($data);

        return redirect('contato')->with('enviado', true);
    }

    private function sendMail($data)
    {
        if (!$email = Contato::first()->email) {
            return false;
        }

        Mail::send('emails.contato', $data, function ($m) use ($email, $data) {
            $m->to($email, config('app.name'))
                ->subject('[CONTATO] ' . config('app.name'))
                ->replyTo($data['email'], $data['nome']);
        });
    }

    public function postMaisInformacoes(ContatosInformacoesRequest $request, $produto_id)
    {
        $data = $request->all();
        $data['produto_id'] = $produto_id;
        
        ContatoInformacao::create($data);
        $this->sendMailInformacoes($data);

        return redirect()->back()->with('enviado', true);
    }

    private function sendMailInformacoes($data)
    {
        if (!$email = Contato::first()->email) {
            return false;
        }
        $produto = Produto::where('id', $data['produto_id'])->first();

        Mail::send('emails.informacoes', ['data' => $data, 'produto' => $produto], function ($m) use ($email, $data) {
            $m->to($email, config('app.name'))
                ->subject('[CONTATO] ' . config('app.name'))
                ->replyTo($data['email'], $data['nome']);
        });
    }
}

laravel/app/Http/Controllers/Painel/ContatosController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\ContatosRequest;
use App\Models\Contato;

class ContatosController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contatos.edit', compact('contato'));
    }

    public function update(ContatosRequest $request, Contato $contato)
    {
        try {
            $input = $request->all();

            $contato->update($input);

            return redirect()->route('painel.contatos.index')->with('success', 'Informações alteradas com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/contatos/informacoes/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>Mais Informações</h2>
</legend>

@if(!count($contatosinfos))
<div class="alert alert-warning" role="alert">Nenhuma mensagem recebida.</div>
@else
<table class="table table-striped table-bordered table-hover data-table">
    <thead>
        <tr>
            <th>Data</th>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Produto</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($contatosinfos as $contato)

        <tr class="tr-row @if(!$contato->lido) warning @endif">
            <td data-order="{{ $contato->created_at_order }}">{{ $contato->created_at }}</td>
            <td>{{ $contato->nome }}</td>
            <td>
                <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $contato->email }}" style="margin-right:5px;border:0;transition:background .3s">
                    <span class="glyphicon glyphicon-copy"></span>
                </button>
                {{ $contato->email }}
            </td>
            @php
            $produto = $produtos->find($contato->produto_id)->titulo;
            @endphp
            <td>{{ $produto }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.contatos.mais-informacoes.destroy', $contato->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.contatos.mais-informacoes.show', $contato->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-align-left" style="margin-right:10px;"></span>Ler mensagem
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>

                    <a href="{{ route('painel.contatos.mais-informacoes.toggle', $contato->id) }}" class="btn btn-sm pull-left {{ ($contato->lido ? 'btn-warning' : 'btn-success') }}">
                        <span class="glyphicon small {{ ($contato->lido ? 'glyphicon-repeat' : 'glyphicon-ok') }}"></span>
                    </a>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>

        @endforeach
    </tbody>
</table>
@endif

@stop

laravel/resources/views/painel/contatos/informacoes/show.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2>Mais Informações</h2>
</legend>

<div class="form-group">
    <label>Data</label>
    <div class="well">{{ $contato->created_at }}</div>
</div>

<div class="form-group">
    <label>Nome</label>
    <div class="well">{{ $contato->nome }}</div>
</div>

<div class="form-group">
    <label>E-mail</label>
    <div class="well">
        <button class="btn btn-info btn-sm clipboard" data-clipboard-text="{{ $contato->email }}" style="margin-right:5px;border:0;transition:background .3s">
            <span class="glyphicon glyphicon-copy"></span>
        </button>
        {{ $contato->email }}
    </div>
</div>

@if($contato->telefone)
<div class="form-group">
    <label>Telefone</label>
    <div class="well">{{ $contato->telefone }}</div>
</div>
@endif

<div class="form-group">
    <label>Mensagem</label>
    <div class="well">{{ $contato->mensagem }}</div>
</div>

<div class="form-group">
    <label>Produto</label>
    <div class="well">{{ $produto->titulo }}</div>
</div>

<a href="{{ route('painel.contatos.mais-informacoes.index') }}" class="btn btn-default btn-voltar">Voltar</a>

@stop